remote_theme: piazzai/cvless@master

# site settings

title: Pilvipalvelut
description:  Tervetuloa sivustolleni!
taglong: Tervetuloa GitHub Pages-sivustolleni!
tagshort: Tervetuloa sivustolleni!
url: https://heli-dl.github.io/pilvipalvelut/

# author settings

author:
  name: Heli De Lorme
  email: heli.de.lorme@myy.haaga-helia.fi
photo: assets/photos/profile.jpg


# social media links

social:
  github: Heli-DL
  linkedin: heli-de-lorme


plugins:
  - jekyll-include-cache






