remote_theme: piazzai/cvless@master

# site settings

title: Pilvipalvelut
description:  Tervetuloa sivustolleni!
taglong: Tervetuloa GitHub Pages-sivustolleni!
tagshort: Tervetuloa sivustolleni!
url: https://heli-dl.github.io/pilvipalvelut/
baseurl: ""
permalink: pretty
repo: https://github.com/username/username.github.io

# author settings

author:
  name: Heli De Lorme
  email: heli.de.lorme@myy.haaga-helia.fi
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: Heli-DL
  linkedin: heli-de-lorme

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
